### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by RamilNazmiev** [galiaMuslimova/MetaLamp-Layout-#1]
1  все переключатели , (радио кнопки ,chebox , togle  ) должны быть отдельными компонентами 
![image](https://user-images.githubusercontent.com/94169565/154079457-182652b3-d6f4-4723-92da-7d119da41d75.png)

**Comment by galiaMuslimova** [comment]
Исправила для radio. Toggle уже был отдельным компонентом, убрала для него form (может это имелось в виду).
