### ISSUE TITLE
Неточности вёрстки

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#15]
На странице forms поехала вёрстка и не раскрывается календарь

![image](https://user-images.githubusercontent.com/43137324/160432289-3d41c813-8914-437a-b985-37e081322654.png)

У текстовых полей обрезаны линии границ на углах

![image](https://user-images.githubusercontent.com/43137324/160432655-2d1459b9-0516-4c96-9716-14c73e2a4c96.png)

Элемент кликабельный, но курсор остался обычный

![image](https://user-images.githubusercontent.com/43137324/160432867-580e1308-b5ef-4324-8619-37f2713b7e67.png)

Линия толще, чем в макете

![image](https://user-images.githubusercontent.com/43137324/160433047-4a7c8e23-abb4-4e67-bdc9-bae94f97d60b.png)
![image](https://user-images.githubusercontent.com/43137324/160433918-31840fc8-6fc1-4f67-a708-fc42f8f317d1.png)

У этой кнопки не хватает hover эффекта

![image](https://user-images.githubusercontent.com/43137324/160433225-6fcf1f9c-a389-49e7-b845-492fa19b66bf.png)

У таких кликабельных элементов лучше отключать возможность выделения текста

![image](https://user-images.githubusercontent.com/43137324/160433542-831966b2-7c9a-4243-b16f-a7a1cda80070.png)
![image](https://user-images.githubusercontent.com/43137324/160433578-b7258499-0eb6-4034-9ff4-f787c65ff357.png)
![image](https://user-images.githubusercontent.com/43137324/160433632-41df3edc-b0e1-4b91-8919-49ad26789532.png)

**Comment by Everrest1** [comment]
Надо добавить небольшой отступ)

![image](https://user-images.githubusercontent.com/43137324/161495142-c0624841-ab92-430e-9336-7f15eacfd2c1.png)

Пункты меню "прыгают" при наведении

![7bbeb2ae-9327-4169-977d-8c3577940813](https://user-images.githubusercontent.com/43137324/161495692-0f583149-531d-42e6-8320-cd50566964b4.gif)

В выпадающем календаре не хватает управляющих кнопок "очистить" и "применить". И очень хотелось бы видеть ячейки в форме окружностей, как на макете

![image](https://user-images.githubusercontent.com/43137324/161496744-5f57c31b-aaec-4280-8173-d4b2189d791b.png)

Углы снова срезаны

![image](https://user-images.githubusercontent.com/43137324/161496995-030a0112-61e4-4fc7-9e5f-503406dc5e8b.png)

Немного съехало вертикальное выравнивание, должно быть по центру

![image](https://user-images.githubusercontent.com/43137324/161497589-d0786374-6c57-415f-874e-6436b447ec0b.png)

**Comment by Everrest1** [comment]
> Пункты меню "прыгают" при наведении
> 
> ![7bbeb2ae-9327-4169-977d-8c3577940813](https://user-images.githubusercontent.com/43137324/161495692-0f583149-531d-42e6-8320-cd50566964b4.gif)

Для селекта гостей не хватает кнопок "применить" и "очистить"

![image](https://user-images.githubusercontent.com/43137324/162680503-bb19b2d5-caa5-44d9-96ed-f4bef398edf2.png)

![image](https://user-images.githubusercontent.com/43137324/162680002-7188263a-8fc6-4b60-b82f-ce5d7c857798.png)

**Comment by galiaMuslimova** [comment]
Чтобы меню не прыгало, заменила bold на stroke, допустимо?

**Comment by Everrest1** [comment]
Поле не должно быть редактируемым

![image](https://user-images.githubusercontent.com/43137324/163767902-47259345-72c0-481c-bc26-6fa8652e69e3.png)

На главной странице тоже нужно поправить

![a0b0d197-7d58-47f0-a78c-d72e274b2fc2](https://user-images.githubusercontent.com/43137324/163768286-fa0644bf-7f09-4a22-978a-9c2aa33d31ca.gif)

Съехало вертикальное выравнивание

![image](https://user-images.githubusercontent.com/43137324/163768456-dfc77f3e-1a23-4a74-9d9a-fb2375ce6614.png)
