### ISSUE TITLE
Независимость блоков

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#16]
Блоки не должны знать о внутренней структуре других блоков [п.4.4.](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4). Т.е. использовать селекторы одного блока внутри другого нельзя, иначе это приведёт к множеству неочевидных багов, которые потом будет сложно найти. Использовать другие блоки можно инициализировав их инстансы и вызывая публичные методы

![image](https://user-images.githubusercontent.com/43137324/160434599-504d82c5-95ff-4dd3-9c23-b44ca296667e.png)

**Comment by Everrest1** [comment]
Селекторы блока могут находиться только в соответствующем css файле в директории этого блока. Иначе стили могут начать переопределяться и придётся искать их по всему проекту, что займёт кучу времени и сил

![image](https://user-images.githubusercontent.com/43137324/161499030-fa75a100-822b-4dc3-b9d0-4b0453da04a1.png)

**Comment by Everrest1** [comment]
В таких случаях удобнее было бы продолжить работать инстансом input, и использовать для получения/передачи значений методы set/get value.

![image](https://user-images.githubusercontent.com/43137324/161505294-430bd47e-1e1a-4644-9eb7-504d7a07466d.png)

Довольно странной получилась работа с одним инстансом на два инпута. Логичнее было бы придерживаться правила один инстанс - один блок, куда проще ориентироваться в коде, если все блоки имеют похожую структуру и не нужно разбираться и запоминать конкретные особенности каждого

![image](https://user-images.githubusercontent.com/43137324/161505558-59eace7e-4534-49dc-b750-82c01f091338.png)

**Comment by Everrest1** [comment]
Модификаторы предназначены для указания свойств или поведения, которые они модифицируют в блоке, но ни как не для указания принадлежности блока к контексту

![image](https://user-images.githubusercontent.com/43137324/162684387-aae86944-5999-4d87-b1e6-a901440b7647.png)

**Comment by galiaMuslimova** [comment]
заменила модификатор на ид, тоже сомневаюсь можно ли использовать ид. Не нашла в best practices, но помню что где-то не рекомендовали использовать ид, но строгого запрета не было. Если ид можно, то правильно ли название в контексте бэм.

**Comment by Everrest1** [comment]
> заменила модификатор на ид, тоже сомневаюсь можно ли использовать ид. Не нашла в best practices, но помню что где-то не рекомендовали использовать ид, но строгого запрета не было. Если ид можно, то правильно ли название в контексте бэм.

Эту задачу можно решить не привязываясь к идентификаторам, т.е. блок calendar не должен знать где он использован и к какому другому блоку принадлежит
