### ISSUE TITLE
Структура блоков

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#18]
Когда мы делим страницу на БЭМ блоки, мы стараемся выделить максимально мелкие независимые элементы. Блоки крупнее, могут содержать другие блоки. Смысл в том, что блок - это вполне конкретная сущность, которую можно увидеть на странице и однозначно назвать. Исходя их этого, блок не может существовать, не имея своей структуры или вёрстки

![image](https://user-images.githubusercontent.com/43137324/162682680-eca2fbc4-9427-4383-a3f9-642174294778.png)

**Comment by galiaMuslimova** [comment]
Могу ли я вообще задавать абстрактные классы, и если да, то как их оформить? Вынести отдельно как Observer? Или лучше без них, и дублировать код?

**Comment by Everrest1** [comment]
Я думаю в абстракции нет необходимости и рассмотрел бы варианты объединения почти этих одинаковых блоков в один, либо наследование одного из блоков от другого

**Comment by Everrest1** [comment]
Когда нужно переопределить стили библиотеки, это делается строго внутри селекторов блока, чтобы стили применились локально только для этого конкретного блока

![image](https://user-images.githubusercontent.com/43137324/163775884-025c398f-5ab5-4172-b5eb-b74b08f364f2.png)

**Comment by Everrest1** [comment]
Возможно это тоже стоит вынести в параметры и обрабатывать с помощью массивов

![image](https://user-images.githubusercontent.com/43137324/164760777-4b1c8c1c-0fe0-436e-b1a8-62ad30bf046f.png)

**Comment by Everrest1** [comment]
Здесь определенно должен приходить сверху массив с пунктами навигации

![image](https://user-images.githubusercontent.com/43137324/164761063-e6f70563-c629-487a-9330-f03b46b4c1a5.png)

**Comment by Everrest1** [comment]
И здесь)

![image](https://user-images.githubusercontent.com/43137324/164761189-c86f9723-4910-4f65-b70b-8f35b504e24f.png)
