### ISSUE TITLE
Инициализация инстансов js

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#19]
Если придерживаться принципа, что блок - это отдельная конкретная сущность страницы, у которой есть своя структура, стили, поведение, то было бы логично что для каждой отдельной сущности данного блока на странице должен быть отдельный инстанс. Т.е. когда инициализируется инстанс класса Carousel, то он получает только один DOM-элемент блока на странице и работает только с ним. Если блоков на станице 10, то будет инициализировано 10 инстансов Carousel

Код ниже работает со всеми инстансами внутри $root одновременно

![image](https://user-images.githubusercontent.com/43137324/162684853-a7f60570-437c-481b-b4ac-ddb73e00da3e.png)

**Comment by galiaMuslimova** [comment]
Не очень поняла тут. Дело в том, что блок catalog-list формирует для каждой карточки свой catalog-item, затем этот catalog-item создает свой carousel. Потому все карточки каталога независимы. Корнем для карусели служит только один блок, одна карточка каталога. 
Код ниже работает со всеми инстансами внутри $root одновременно. Да, и чтобы карусель был один, я корень задаю как один элемент.  Исправлять нужно? Не знаю смогла ли объяснить.

**Comment by Everrest1** [comment]
Так, да. в этом плане всё верно, меня запутало имя itemList, переименуй пж в slides

А второй момент: зачем методы slideToRight и slideToLeft сделаны статическими?

![image](https://user-images.githubusercontent.com/43137324/163120059-28461213-26de-463f-bd6d-5de13c194fb3.png)

**Comment by galiaMuslimova** [comment]
Методы не работаю с this, так как двигать надо и слайд и индикатор. При использовании для обоих методы получаются объемными, с повторами кода, а так есть статический метод который может быть использован для любого аналогичного списка.
