### ISSUE TITLE
carousel

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#22]
Определение функции requareAll  однозначно должно быть не здесь

![image](https://user-images.githubusercontent.com/43137324/164169289-42bf4416-194c-4c29-b0cd-b25b79955ea1.png)

Подобные шаблоны обычно выполняются с помощью циклов

![image](https://user-images.githubusercontent.com/43137324/164169584-0f3bc3a1-9c68-4948-bb71-df858861a653.png)

Для чего ещё раз оборачивать $firstItem, который и так является jQuery объектом?

![image](https://user-images.githubusercontent.com/43137324/164169871-8c6008f8-8d01-41a5-997c-0a02666f7d57.png)

**Comment by galiaMuslimova** [comment]
Сделала вместо функции requireAll переменную, но, наверно, имелось в виду не это. Нужно переносить в js? Но, тогда и создание dom элементов перейдет в js.

**Comment by Everrest1** [comment]
Можно вынести определение функции за пределы миксина

**Comment by galiaMuslimova** [comment]
![carousel](https://user-images.githubusercontent.com/35797621/164911675-b83a4cc2-6d0d-4a6d-adf0-f8d5a48a63fc.jpg)
Можно оставить в таком виде? Перед миксином функцию нельзя добавить, после тоже, в другой pug файл не хотелось бы выносить.
