### ISSUE TITLE
Использование location

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#24]
Почему был сделан выбор в пользу использования `location`, а не тега `a` с атрибутом `href`? Это как минимум семантически неверно

![image](https://user-images.githubusercontent.com/43137324/165130377-02339e4e-1bdf-4d97-a829-47ec87f8a7dc.png)

**Comment by galiaMuslimova** [comment]
так как предполагалось, что при клике на эти кнопки будет не просто переход по ссылке, но и передача некоторых данных.  Исправить на обычные ссылки?

**Comment by Everrest1** [comment]
Да, исправь плиз

**Comment by galiaMuslimova** [comment]
Для логотипа ссылку убрала.
