### ISSUE TITLE
Perfect pixel

### ISSUE THREAD

**Issue by Everrest1** [galiaMuslimova/MetaLamp-Layout-#26]
Надо подправить отступы

![image](https://user-images.githubusercontent.com/43137324/165570122-2c410112-0bc2-4f2d-b649-113f1bd3e5f6.png)
![image](https://user-images.githubusercontent.com/43137324/165570687-8231187d-9bc5-4cdb-be6d-898cb4d6807d.png)
![image](https://user-images.githubusercontent.com/43137324/165571350-905a54fe-2a43-46e0-a208-d38e0a9b75ca.png)
![image](https://user-images.githubusercontent.com/43137324/165572997-b271f224-bf76-42c7-b15e-02d0c395c418.png)
![image](https://user-images.githubusercontent.com/43137324/165573424-0644856c-c453-4bf8-8465-be21cc9043d7.png)

**Comment by Everrest1** [comment]
Нужно выровнять контент

![image](https://user-images.githubusercontent.com/43137324/166633408-b64c10a7-2c2d-4659-8ad7-674abd13c692.png)

**Comment by galiaMuslimova** [comment]
Еще раз посмотри, пожалуйста, у меня в порядке, изменений незакомиченных нет.
![pp](https://user-images.githubusercontent.com/35797621/166692574-1524f261-baa0-466b-9bbd-422b897afba1.png)
