### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by sodiqit** [galiaMuslimova/MetaLamp-Layout-#30]
подгрузил картинки из папки figma-images 
![image](https://user-images.githubusercontent.com/47000555/177109723-6a82dee4-e340-4a80-82bf-1d2aaca4aa7b.png)
такое почти со всеми страница, проверь плз)

**Comment by sodiqit** [comment]
также по макетам черный цвет у года
![image](https://user-images.githubusercontent.com/47000555/177110052-62a160ba-5843-44a6-96c1-03c721470e40.png)

**Comment by galiaMuslimova** [comment]
Поправила, но у меня почему-то сдвиг был не такой сильный. Проверяла при ширине окна 1440
