### ISSUE TITLE
dropdown

### ISSUE THREAD

**Issue by sodiqit** [galiaMuslimova/MetaLamp-Layout-#31]
лучше показывать тогда сколько спален и ванных комнат)
![image](https://user-images.githubusercontent.com/47000555/179686147-b6e3d4af-ae03-4b21-a63a-c5870f08a9a9.png)

**Comment by sodiqit** [comment]
еще такой баг есть 
![image](https://user-images.githubusercontent.com/47000555/181879722-1dfc6435-2793-4c6d-a784-18c041928e79.png)

**Comment by galiaMuslimova** [comment]
fix
