### ISSUE TITLE
button

### ISSUE THREAD

**Issue by sodiqit** [galiaMuslimova/MetaLamp-Layout-#32]
почему то кнопка на странице входа - ссылка 
![image](https://user-images.githubusercontent.com/47000555/179686428-81a42139-f332-4c11-83af-1d3d433b59e0.png)
тоже самое и на странице регистрации. 

Можешь пожалуйста проверить по всему проекту, чтобы были нужные теги на своих местах

**Comment by sodiqit** [comment]
![image](https://user-images.githubusercontent.com/47000555/179686609-92f25bd2-9ad0-493d-8e15-8bee9eabae86.png)

**Comment by galiaMuslimova** [comment]
кнопки в header оставила ссылками(a), в формах сделала кнопками(button). в проекте все кнопки проверила
