### ISSUE TITLE
Pixel perfect 

### ISSUE THREAD

**Issue by RamilNazmiev** [galiaMuslimova/MetaLamp-Layout-#6]
1 Создай папку для хранения всех изображений из figma , в корне проекта 

> 

2 

> ![image](https://user-images.githubusercontent.com/94169565/155650645-d6de2123-fbb7-4a91-b7e0-d4ea8e929b54.png)

3 тут надо поработать со всей 

> страницей

![image](https://user-images.githubusercontent.com/94169565/155651023-fbbb8132-0d69-4660-936b-3eee2bcc905e.png)

4 тут тоже надо подправить 

> 

![image](https://user-images.githubusercontent.com/94169565/155651297-4850f817-938a-4c47-b309-9cc6846a093e.png)

**Comment by galiaMuslimova** [comment]
У меня при локальном запуске таких больших неточностей не было. Посмотрю потом еще как выглядит через github pages. Пока прошлась по всем файлам, поправила pixel perfect. Для ui-kit более грубо.
